### ISSUE TITLE
Unable to receive swapped HBARS to contract owner address when the swapping token has a fee associated

### ISSUE THREAD

**Issue by nandita2021** [saucerswaplabs/saucerswap-periphery#1]
Lets say I have a contract name ABC.sol on Hedera 
Moreover, I have a Fungible Token `DemoCheck` that has [4% fracional fee attahced going directly to the ABC.sol on each token txn](https://testnet.saucerswap.finance/swap/HBAR/0.0.4416676) .

**NOTE that `ABC.sol` owner and `DemoCheck` owner is the same operator**

ABC.sol has around 100k DemoCheck tokens.

The contract has a swap fn that swaps the `DemoCheck` to `HBAR` using  - 
```
        .swapExactTokensForETHSupportingFeeOnTransferTokens(
            tokensToSwap,
            0, // accept any amount of WHBAR
            path,
            recipientAddress, 
            block.timestamp
        );
```

`uniswapV2Router` is initialized with SaucerSwapV1RouterV3: [0.0.19264](https://hashscan.io/testnet/contract/0.0.19264) obtained from - https://docs.saucerswap.finance/developer/contract-deployments

The [HBAR/DemoCheck liquidity pool](https://testnet.saucerswap.finance/liquidity/0.0.4418448/manage-position) is already setup on SaucerSwap testnet.

Now the problem is that `swapExactTokensForETHSupportingFeeOnTransferTokens` call always works fine as long as the `recipientAddress` === `operatorAddress`. The [Txn fails](https://hashscan.io/testnet/transactionsById/0.0.4398179-1717694823-336585592). 

However, when I set `recipientAddress` to any `non-operator` address, then [everything goes smooth](https://hashscan.io/testnet/transactionsById/0.0.4398179-1717693562-746092287). 

**Note that the only difference between two transactions was that the `recipientAddress` was of operator in first case and non-operator in second case. Rest everything is same** 

**Also note that this issue occurs only when the `DemoCheck` token has a fee associated to it (4% in my case). I also tried the swap for non-fee token when `recipientAddress` === `operatorAddress`. and it worked fine.**

**Comment by littletarzan** [comment]
Hello,

Can you verify your ABC.sol contract or provide a link to the source code? Does your ABC.sol contract have a payable receive() function?

**Comment by nandita2021** [comment]
> Hello,
> 
> Can you verify your ABC.sol contract or provide a link to the source code? Does your ABC.sol contract have a payable receive() function?



> Hello,
> 
> Can you verify your ABC.sol contract or provide a link to the source code? Does your ABC.sol contract have a payable receive() function?

Yes, I do have payable recieve in ABC.sol - 


![image](https://github.com/saucerswaplabs/saucerswap-periphery/assets/128652723/88dee90d-d32a-4fd2-bd54-c4ac25b7ed58)


Unfortunately, I think I won't be able to share the complete contracts code due to privacy reasons. However, I believe I can show the things you need.

Imports -
![image](https://github.com/saucerswaplabs/saucerswap-periphery/assets/128652723/013dee11-b2f1-4399-b87f-7080e75c5bc4)


Functions -

`  receive() external payable {}`

and

 ```
   function swapTokens(uint256 tokensToSwap) public onlyOwner {
        address[] memory path = new address[](2);
        path[0] = _tokenAddress; //0.0.4416676
        path[1] = uniswapV2Router.whbar();

        approve(_tokenAddress, address(uniswapV2Router), tokenAmount);

        uniswapV2Router.swapExactTokensForETHSupportingFeeOnTransferTokens(
            tokensToSwap,
            0, // accept any amount of WHBAR
            path,
            recipientAddress, 
            block.timestamp
        );
    }
```

**Comment by littletarzan** [comment]
I am not sure I can help without seeing the contract. I see from the failed transaction that the function originally called is `swapTokens(uint256)`, which is a function in your contract.

![image](https://github.com/saucerswaplabs/saucerswap-periphery/assets/91925163/75a7dc00-0f63-48b4-aceb-114d85c2599b)

**Comment by nandita2021** [comment]
> I am not sure I can help without seeing the contract. I see from the failed transaction that the function originally called is `swapTokens(uint256)`, which is a function in your contract.
> 
> ![image](https://private-user-images.githubusercontent.com/91925163/337444248-75a7dc00-0f63-48b4-aceb-114d85c2599b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MDkzMzIsIm5iZiI6MTcxNzcwOTAzMiwicGF0aCI6Ii85MTkyNTE2My8zMzc0NDQyNDgtNzVhN2RjMDAtMGY2My00OGI0LWFjZWItMTE0ZDg1YzI1OTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDIxMjM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzNzMzMDU3OGFhYTM5ZmU4ZDhlMzc1ZTE0MDZmNjJiNmFmNjg3OGIyNDNkZTg3MzQyMmEwMjcwMjE2MTcyZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mlJzTmMZHt-EOQAjqzkiKWKd3YHPwsYtEchzR3gOicA)

I see. The fn above is swapTokens. I fixed the name in previous comment. Let me check with my managers to see what we can do
